version: '3.4'
services:
  web:
    build: .
    env_file:
      - .env
      - .env.local
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3002:3000'
  db:
    image: redis
    restart: always
    env_file:
      - .env
      - .env.local
    volumes:
      - cache:/data
volumes:
  cache:
